
# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_31 = Integer(31); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_61 = Integer(61)
p = (_sage_const_2 **_sage_const_31 ) - _sage_const_1 
q = (_sage_const_2 **_sage_const_61 ) - _sage_const_1 
n = p * q
mString = "HELLOWORLD"
mDecimal = [ord(x) for x in mString]
print list(reversed(mDecimal))
# mDecimal = ZZ(list(reversed(mDecimal)), 100)

